jobs:
- job: macOS
  pool:
    vmImage: macOS-10.14
  steps:
    - bash: |
        set -e
        brew update
        HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/kabel/homebrew-php-ext"
        mkdir -p "$HOMEBREW_TAP_DIR"
        rm -rf "$HOMEBREW_TAP_DIR"
        ln -s "$PWD" "$HOMEBREW_TAP_DIR"
        brew test-bot
      displayName: Run brew test-bot
